name: deltars-lakefs-demo
services:
  lakefs:
    image: treeverse/lakefs:1.56
    pull_policy: always
    depends_on:
      - minio-bucket-setup
    ports:
      - "8000:8000"
    environment:
      - LAKEFS_DATABASE_TYPE=local
      - LAKEFS_BLOCKSTORE_TYPE=s3
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE=true
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT=http://minio:9000
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=minioDeltaUser
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY=minioDeltaSecretKey
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=some random secret string
      - LAKEFS_LOGGING_LEVEL=INFO
      - LAKEFS_STATS_ENABLED=${LAKEFS_STATS_ENABLED:-1}
      - LAKEFS_INSTALLATION_USER_NAME=delta-rs
      - LAKEFS_INSTALLATION_ACCESS_KEY_ID=DELTARSACCESSKEY
      - LAKEFS_INSTALLATION_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - LAKECTL_CREDENTIALS_ACCESS_KEY_ID=DELTARSACCESSKEY
      - LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - LAKECTL_SERVER_ENDPOINT_URL=http://localhost:8000
    entrypoint: ["/bin/sh", "-c"]
    command:
        - |
          lakefs run --local-settings &
          echo "---- Creating repository ----"
          wait-for -t 60 lakefs:8000 -- lakectl repo create lakefs://bronze s3://bronze || true
          wait-for -t 60 lakefs:8000 -- lakectl repo create lakefs://silver s3://silver || true
          wait-for -t 60 lakefs:8000 -- lakectl repo create lakefs://gold s3://gold || true
          echo ""
          echo "lakeFS Web UI: http://127.0.0.1:8000/      >(.＿.)<"
          echo "                                             (  )_ "
          echo ""
          echo "                Access Key ID    : $$LAKEFS_INSTALLATION_ACCESS_KEY_ID"
          echo "                Secret Access Key: $$LAKEFS_INSTALLATION_SECRET_ACCESS_KEY"
          echo ""
          echo "-------- Let's go and have axolotl fun! --------"
          echo ""
          wait
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: ["minio", "server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: minioDeltaUser
      MINIO_ROOT_PASSWORD: minioDeltaSecretKey
  minio-bucket-setup:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set miniolakefs http://minio:9000 minioDeltaUser minioDeltaSecretKey;
      /usr/bin/mc mb miniolakefs/bronze/;
      /usr/bin/mc mb miniolakefs/silver/;
      /usr/bin/mc mb miniolakefs/gold/;
      exit 0;
      "
networks:
  default:
    name: bagel
